//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string email_id { get; set; }
        public string profile_pic { get; set; }
        public int status_id { get; set; }
        public int role_id { get; set; }
        public int department_id { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
        public string employee_code { get; set; }
    }
}
