//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class EU_Check
    {
        public int eu_check_id { get; set; }
        public int way_bill_id { get; set; }
        public string eu_checked_by { get; set; }
        public int reject_number { get; set; }
    }
}
