//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange_Rate
    {
        public int exchange_rate_id { get; set; }
        public int from_currency_id { get; set; }
        public int to_currency_id { get; set; }
        public int month_id { get; set; }
        public decimal exchange_rate1 { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
    }
}
