//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Heirarchy
    {
        public int goods_heirarchy_id { get; set; }
        public string heirarchy { get; set; }
        public Nullable<int> parent_id { get; set; }
    }
}
