//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int goods_id { get; set; }
        public int goods_type_id { get; set; }
        public string goods_name { get; set; }
        public int status_id { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
