//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month
    {
        public int month_id { get; set; }
        public int quarter_id { get; set; }
        public int year_id { get; set; }
        public string month_code { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
        public Nullable<int> month_number { get; set; }
        public string month1 { get; set; }
    }
}
