//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public int ship_id { get; set; }
        public string ship_name { get; set; }
        public string ship_code_1 { get; set; }
        public string ship_code_2 { get; set; }
        public string ship_code_3 { get; set; }
        public int status_id { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
