//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Assign_Way_Bill
    {
        public int e_assign_tax_id { get; set; }
        public int e_way_bill_id { get; set; }
        public int user_id { get; set; }
        public bool status { get; set; }
        public System.DateTime end_date { get; set; }
    }
}
