//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Calculated_Penalty_Config
    {
        public int e_calculated_penalty_config_id { get; set; }
        public int e_way_bill_id { get; set; }
        public int Penalty_Percentage { get; set; }
        public decimal Total_sos { get; set; }
        public decimal Penalty_sos { get; set; }
        public decimal grand_total_sos { get; set; }
        public decimal calculated_sos_part { get; set; }
        public decimal calculated_sos_amount { get; set; }
        public decimal Total_usd { get; set; }
        public decimal Penalty_usd { get; set; }
        public decimal grand_total_usd { get; set; }
        public decimal calculated_usd_part { get; set; }
        public decimal calculated_usd_amount { get; set; }
        public decimal exchange_rate_usd_to_sos { get; set; }
        public System.DateTime calculated_date { get; set; }
        public int employee_id { get; set; }
    }
}
