//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Penaltized_Goods_Details
    {
        public int e_penaltized_goods_details_id { get; set; }
        public int e_way_bill_id { get; set; }
        public int goods_id { get; set; }
        public int unit_of_measure_id { get; set; }
        public int total_quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<int> currency_id { get; set; }
        public bool is_damaged { get; set; }
    }
}
