//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Tally_Sheet
    {
        public int tally_sheet_id { get; set; }
        public string tally_sheet_code { get; set; }
        public int employee_id { get; set; }
        public int ship_departure_id { get; set; }
    }
}
