//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_TempDisplay1
    {
        public int temp_display1_id { get; set; }
        public int way_bill_id { get; set; }
        public int Goods_Id { get; set; }
        public string goods_name { get; set; }
        public string Unit_Price { get; set; }
        public string calculated_Tariff { get; set; }
        public int toal_Quantity { get; set; }
        public string Unit_Code { get; set; }
        public string Base_Taxation { get; set; }
        public string Total { get; set; }
        public bool is_damaged { get; set; }
    }
}
