//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Way_Bill
    {
        public int e_way_bill_id { get; set; }
        public string e_way_bill_code { get; set; }
        public string e_way_bill_name { get; set; }
        public int export_id { get; set; }
        public int exporter_id { get; set; }
        public bool is_calculated { get; set; }
        public string mark { get; set; }
    }
}
