//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public int export_id { get; set; }
        public int exporter_id { get; set; }
        public int exporting_status_id { get; set; }
        public int ship_departure_id { get; set; }
        public string export_code { get; set; }
        public string e_bollete_dogonale_code { get; set; }
        public Nullable<int> e_way_bill_id { get; set; }
        public int e_payment_id { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
