//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial_Quarter
    {
        public int financial_quarter_id { get; set; }
        public int financial_year_id { get; set; }
        public string financial_quarter_code { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
