//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importer
    {
        public int importer_id { get; set; }
        public string importer_first_name { get; set; }
        public string importer_middle_name { get; set; }
        public string importer_last_name { get; set; }
        public string importer_email_id { get; set; }
        public string importer_mob_no { get; set; }
        public int importer_type_id { get; set; }
        public int importer_country_id { get; set; }
        public int status_id { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
