//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Config
    {
        public int payment_config_id { get; set; }
        public decimal sos { get; set; }
        public decimal usd { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime end_date { get; set; }
    }
}
