//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Puntland_Port_Taxation_DBEntities : DbContext
    {
        public Puntland_Port_Taxation_DBEntities()
            : base("name=Puntland_Port_Taxation_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Financial_Period> Financial_Period { get; set; }
        public DbSet<Financial_Quarter> Financial_Quarter { get; set; }
        public DbSet<Financial_Year> Financial_Year { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<Function_Role_Map> Function_Role_Map { get; set; }
        public DbSet<Geography> Geographies { get; set; }
        public DbSet<Goods_Category> Goods_Category { get; set; }
        public DbSet<Goods_Subcategory> Goods_Subcategory { get; set; }
        public DbSet<Goods_Type> Goods_Type { get; set; }
        public DbSet<Importer> Importers { get; set; }
        public DbSet<Importer_Type> Importer_Type { get; set; }
        public DbSet<Importing_Status> Importing_Status { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<Quarter> Quarters { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Ship> Ships { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Year> Years { get; set; }
        public DbSet<Levi_Type> Levi_Type { get; set; }
        public DbSet<Goods_Heirarchy> Goods_Heirarchy { get; set; }
        public DbSet<EU_Check> EU_Check { get; set; }
        public DbSet<Exchange_Rate> Exchange_Rate { get; set; }
        public DbSet<Good> Goods { get; set; }
        public DbSet<Goods_Tariff> Goods_Tariff { get; set; }
        public DbSet<Import> Imports { get; set; }
        public DbSet<Levi> Levis { get; set; }
        public DbSet<Levi_Entry> Levi_Entry { get; set; }
        public DbSet<Reject_Reason> Reject_Reason { get; set; }
        public DbSet<Tally_Sheet> Tally_Sheet { get; set; }
        public DbSet<Unit_Of_Measure> Unit_Of_Measure { get; set; }
        public DbSet<Way_Bill> Way_Bill { get; set; }
        public DbSet<TempDisplay2> TempDisplay2 { get; set; }
        public DbSet<Payment_details> Payment_details { get; set; }
        public DbSet<Payment_mode> Payment_mode { get; set; }
        public DbSet<Payment_Config> Payment_Config { get; set; }
        public DbSet<Assign_Way_Bill> Assign_Way_Bill { get; set; }
        public DbSet<Calculated_Payment_Config> Calculated_Payment_Config { get; set; }
        public DbSet<Calculated_Penalty_Config> Calculated_Penalty_Config { get; set; }
        public DbSet<Payment_Penalty_details> Payment_Penalty_details { get; set; }
        public DbSet<Temp_penalty_Display2> Temp_penalty_Display2 { get; set; }
        public DbSet<Calculated_Levi> Calculated_Levi { get; set; }
        public DbSet<Calculated_Penalty> Calculated_Penalty { get; set; }
        public DbSet<Penaltized_Goods_Details> Penaltized_Goods_Details { get; set; }
        public DbSet<Tally_Sheet_Details> Tally_Sheet_Details { get; set; }
        public DbSet<Temp_Penalty_Display1> Temp_Penalty_Display1 { get; set; }
        public DbSet<TempDisplay1> TempDisplay1 { get; set; }
        public DbSet<Way_Bill_Details> Way_Bill_Details { get; set; }
        public DbSet<E_Way_Bill> E_Way_Bill { get; set; }
        public DbSet<Export> Exports { get; set; }
        public DbSet<E_Calculated_Penalty_Config> E_Calculated_Penalty_Config { get; set; }
        public DbSet<E_Way_Bill_Details> E_Way_Bill_Details { get; set; }
        public DbSet<E_Penaltized_Goods_Details> E_Penaltized_Goods_Details { get; set; }
        public DbSet<E_Assign_Way_Bill> E_Assign_Way_Bill { get; set; }
        public DbSet<E_Calculated_Levi> E_Calculated_Levi { get; set; }
        public DbSet<E_Calculated_Payment_Config> E_Calculated_Payment_Config { get; set; }
        public DbSet<E_Levi> E_Levi { get; set; }
        public DbSet<E_Levi_Entry> E_Levi_Entry { get; set; }
        public DbSet<E_Payment_Config> E_Payment_Config { get; set; }
        public DbSet<E_TempDisplay1> E_TempDisplay1 { get; set; }
        public DbSet<E_TempDisplay2> E_TempDisplay2 { get; set; }
        public DbSet<E_Payment_details> E_Payment_details { get; set; }
        public DbSet<E_Calculated_Penalty> E_Calculated_Penalty { get; set; }
        public DbSet<E_Temp_Penalty_Display1> E_Temp_Penalty_Display1 { get; set; }
        public DbSet<E_Temp_penalty_Display2> E_Temp_penalty_Display2 { get; set; }
        public DbSet<E_Payment_Penalty_details> E_Payment_Penalty_details { get; set; }
        public DbSet<Ship_Arrival> Ship_Arrival { get; set; }
        public DbSet<Ship_Departure> Ship_Departure { get; set; }
        public DbSet<E_Tally_Sheet> E_Tally_Sheet { get; set; }
    
        public virtual int Calculate_Penalty(Nullable<int> way_bill_id, Nullable<int> penalty, Nullable<int> employee_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var penaltyParameter = penalty.HasValue ?
                new ObjectParameter("Penalty", penalty) :
                new ObjectParameter("Penalty", typeof(int));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Calculate_Penalty", way_bill_idParameter, penaltyParameter, employee_idParameter);
        }
    
        public virtual int Calculate_Tax(Nullable<int> way_bill_id, Nullable<int> employee_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Calculate_Tax", way_bill_idParameter, employee_idParameter);
        }
    
        public virtual ObjectResult<Display_Levi_Entries_View_Result> Display_Levi_Entries_View(Nullable<int> levi_entry_id)
        {
            var levi_entry_idParameter = levi_entry_id.HasValue ?
                new ObjectParameter("levi_entry_id", levi_entry_id) :
                new ObjectParameter("levi_entry_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Levi_Entries_View_Result>("Display_Levi_Entries_View", levi_entry_idParameter);
        }
    
        public virtual int Display_Penalty_Details(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Display_Penalty_Details", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual int Display_Tax_Details(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Display_Tax_Details", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<string> Get_Grand_Total(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("Currency_id", currency_id) :
                new ObjectParameter("Currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_Grand_Total", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<Get_Penalty_Grand_Total_Result> Get_Penalty_Grand_Total(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("Currency_id", currency_id) :
                new ObjectParameter("Currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Penalty_Grand_Total_Result>("Get_Penalty_Grand_Total", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<Get_Way_Bill_Assign_User_Result> Get_Way_Bill_Assign_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Way_Bill_Assign_User_Result>("Get_Way_Bill_Assign_User");
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetExchangeRate(Nullable<System.DateTime> of_date)
        {
            var of_dateParameter = of_date.HasValue ?
                new ObjectParameter("of_date", of_date) :
                new ObjectParameter("of_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetExchangeRate", of_dateParameter);
        }
    
        public virtual ObjectResult<GetReport1_Levy_Transactions_1_Result> GetReport1_Levy_Transactions_1(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport1_Levy_Transactions_1_Result>("GetReport1_Levy_Transactions_1", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<GetReport3_Levy_Products_Result> GetReport3_Levy_Products(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport3_Levy_Products_Result>("GetReport3_Levy_Products", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual int Reject_Calculated_Tax(Nullable<int> way_bill_id, Nullable<int> importing_Status, string reason, string reject_From)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var importing_StatusParameter = importing_Status.HasValue ?
                new ObjectParameter("Importing_Status", importing_Status) :
                new ObjectParameter("Importing_Status", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            var reject_FromParameter = reject_From != null ?
                new ObjectParameter("Reject_From", reject_From) :
                new ObjectParameter("Reject_From", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reject_Calculated_Tax", way_bill_idParameter, importing_StatusParameter, reasonParameter, reject_FromParameter);
        }
    
        public virtual ObjectResult<Report_1_Result> Report_1(Nullable<System.DateTime> paid_date)
        {
            var paid_dateParameter = paid_date.HasValue ?
                new ObjectParameter("paid_date", paid_date) :
                new ObjectParameter("paid_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_1_Result>("Report_1", paid_dateParameter);
        }
    
        public virtual int Update_Penaltized_Goods_Details_table(Nullable<int> goods_id, Nullable<int> currency_id, Nullable<decimal> unit_price, Nullable<int> way_bill_id)
        {
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            var unit_priceParameter = unit_price.HasValue ?
                new ObjectParameter("unit_price", unit_price) :
                new ObjectParameter("unit_price", typeof(decimal));
    
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Penaltized_Goods_Details_table", goods_idParameter, currency_idParameter, unit_priceParameter, way_bill_idParameter);
        }
    
        public virtual int Update_Tally_Sheet_Details(Nullable<int> tally_sheet_id)
        {
            var tally_sheet_idParameter = tally_sheet_id.HasValue ?
                new ObjectParameter("tally_sheet_id", tally_sheet_id) :
                new ObjectParameter("tally_sheet_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Tally_Sheet_Details", tally_sheet_idParameter);
        }
    
        public virtual int Update_Way_Bill_table(Nullable<int> goods_id, Nullable<int> currency_id, Nullable<decimal> unit_price, Nullable<int> way_bill_id)
        {
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            var unit_priceParameter = unit_price.HasValue ?
                new ObjectParameter("unit_price", unit_price) :
                new ObjectParameter("unit_price", typeof(decimal));
    
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Way_Bill_table", goods_idParameter, currency_idParameter, unit_priceParameter, way_bill_idParameter);
        }
    
        public virtual int E_Display_Tax_Details(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Display_Tax_Details", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<string> E_Get_Grand_Total(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("Currency_id", currency_id) :
                new ObjectParameter("Currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("E_Get_Grand_Total", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<E_Get_Way_Bill_Assign_User_Result> E_Get_Way_Bill_Assign_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<E_Get_Way_Bill_Assign_User_Result>("E_Get_Way_Bill_Assign_User");
        }
    
        public virtual int E_Update_Way_Bill_table(Nullable<int> goods_id, Nullable<int> currency_id, Nullable<decimal> unit_price, Nullable<int> way_bill_id)
        {
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            var unit_priceParameter = unit_price.HasValue ?
                new ObjectParameter("unit_price", unit_price) :
                new ObjectParameter("unit_price", typeof(decimal));
    
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Update_Way_Bill_table", goods_idParameter, currency_idParameter, unit_priceParameter, way_bill_idParameter);
        }
    
        public virtual int Update_Levi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Levi");
        }
    
        public virtual int Update_Levi_Entry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Levi_Entry");
        }
    
        public virtual int E_Calculate_Tax(Nullable<int> way_bill_id, Nullable<int> employee_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Calculate_Tax", way_bill_idParameter, employee_idParameter);
        }
    
        public virtual ObjectResult<E_Display_Levi_Entries_View_Result> E_Display_Levi_Entries_View(Nullable<int> levi_entry_id)
        {
            var levi_entry_idParameter = levi_entry_id.HasValue ?
                new ObjectParameter("levi_entry_id", levi_entry_id) :
                new ObjectParameter("levi_entry_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<E_Display_Levi_Entries_View_Result>("E_Display_Levi_Entries_View", levi_entry_idParameter);
        }
    
        public virtual int E_Reject_Calculated_Tax(Nullable<int> way_bill_id, Nullable<int> importing_Status)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var importing_StatusParameter = importing_Status.HasValue ?
                new ObjectParameter("Importing_Status", importing_Status) :
                new ObjectParameter("Importing_Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Reject_Calculated_Tax", way_bill_idParameter, importing_StatusParameter);
        }
    
        public virtual int E_Update_Penaltized_Goods_Details_table(Nullable<int> goods_id, Nullable<int> currency_id, Nullable<decimal> unit_price, Nullable<int> way_bill_id)
        {
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            var unit_priceParameter = unit_price.HasValue ?
                new ObjectParameter("unit_price", unit_price) :
                new ObjectParameter("unit_price", typeof(decimal));
    
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Update_Penaltized_Goods_Details_table", goods_idParameter, currency_idParameter, unit_priceParameter, way_bill_idParameter);
        }
    
        public virtual ObjectResult<Display_Release_Result> Display_Release(Nullable<int> way_bill_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Release_Result>("Display_Release", way_bill_idParameter);
        }
    
        public virtual int E_Calculate_Penalty(Nullable<int> way_bill_id, Nullable<int> penalty, Nullable<int> employee_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var penaltyParameter = penalty.HasValue ?
                new ObjectParameter("Penalty", penalty) :
                new ObjectParameter("Penalty", typeof(int));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Calculate_Penalty", way_bill_idParameter, penaltyParameter, employee_idParameter);
        }
    
        public virtual int E_Display_Penalty_Details(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("currency_id", currency_id) :
                new ObjectParameter("currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("E_Display_Penalty_Details", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<E_Display_Release_Result> E_Display_Release(Nullable<int> way_bill_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<E_Display_Release_Result>("E_Display_Release", way_bill_idParameter);
        }
    
        public virtual ObjectResult<E_Get_Penalty_Grand_Total_Result> E_Get_Penalty_Grand_Total(Nullable<int> way_bill_id, Nullable<int> currency_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            var currency_idParameter = currency_id.HasValue ?
                new ObjectParameter("Currency_id", currency_id) :
                new ObjectParameter("Currency_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<E_Get_Penalty_Grand_Total_Result>("E_Get_Penalty_Grand_Total", way_bill_idParameter, currency_idParameter);
        }
    
        public virtual ObjectResult<Cargo_Manifest_Export_Result> Cargo_Manifest_Export(Nullable<int> tally_sheet_id)
        {
            var tally_sheet_idParameter = tally_sheet_id.HasValue ?
                new ObjectParameter("tally_sheet_id", tally_sheet_id) :
                new ObjectParameter("tally_sheet_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo_Manifest_Export_Result>("Cargo_Manifest_Export", tally_sheet_idParameter);
        }
    
        public virtual ObjectResult<Report_1_Export_Result> Report_1_Export(Nullable<System.DateTime> paid_date)
        {
            var paid_dateParameter = paid_date.HasValue ?
                new ObjectParameter("paid_date", paid_date) :
                new ObjectParameter("paid_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_1_Export_Result>("Report_1_Export", paid_dateParameter);
        }
    
        public virtual ObjectResult<Report_1_Import_Result> Report_1_Import(Nullable<System.DateTime> paid_date)
        {
            var paid_dateParameter = paid_date.HasValue ?
                new ObjectParameter("paid_date", paid_date) :
                new ObjectParameter("paid_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_1_Import_Result>("Report_1_Import", paid_dateParameter);
        }
    
        public virtual ObjectResult<GetReport_Levy_Transactions_Export_Result> GetReport_Levy_Transactions_Export(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport_Levy_Transactions_Export_Result>("GetReport_Levy_Transactions_Export", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<GetReport_Levy_Transactions_Export_Rep2_Result> GetReport_Levy_Transactions_Export_Rep2(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport_Levy_Transactions_Export_Rep2_Result>("GetReport_Levy_Transactions_Export_Rep2", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<GetReport_Levy_Transactions_Import_Rep2_Result> GetReport_Levy_Transactions_Import_Rep2(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport_Levy_Transactions_Import_Rep2_Result>("GetReport_Levy_Transactions_Import_Rep2", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<GetReport_Levy_Transactions_Import_Result> GetReport_Levy_Transactions_Import(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport_Levy_Transactions_Import_Result>("GetReport_Levy_Transactions_Import", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<Display_Payment_Result> Display_Payment(Nullable<int> way_bill_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Payment_Result>("Display_Payment", way_bill_idParameter);
        }
    
        public virtual ObjectResult<E_Display_Payment_Result> E_Display_Payment(Nullable<int> way_bill_id)
        {
            var way_bill_idParameter = way_bill_id.HasValue ?
                new ObjectParameter("way_bill_id", way_bill_id) :
                new ObjectParameter("way_bill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<E_Display_Payment_Result>("E_Display_Payment", way_bill_idParameter);
        }
    
        public virtual ObjectResult<Report_4_Export_Result> Report_4_Export(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_4_Export_Result>("Report_4_Export", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    
        public virtual ObjectResult<Report_4_Import_Result> Report_4_Import(Nullable<System.DateTime> date, Nullable<int> month_id, Nullable<int> year_id, Nullable<System.DateTime> date_Interval1, Nullable<System.DateTime> date_Interval2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var month_idParameter = month_id.HasValue ?
                new ObjectParameter("month_id", month_id) :
                new ObjectParameter("month_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var date_Interval1Parameter = date_Interval1.HasValue ?
                new ObjectParameter("Date_Interval1", date_Interval1) :
                new ObjectParameter("Date_Interval1", typeof(System.DateTime));
    
            var date_Interval2Parameter = date_Interval2.HasValue ?
                new ObjectParameter("Date_Interval2", date_Interval2) :
                new ObjectParameter("Date_Interval2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_4_Import_Result>("Report_4_Import", dateParameter, month_idParameter, year_idParameter, date_Interval1Parameter, date_Interval2Parameter);
        }
    }
}
