//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship_Arrival
    {
        public int ship_arrival_id { get; set; }
        public int shipp_id { get; set; }
        public int state_id { get; set; }
        public int day_id { get; set; }
        public string ship_arrival_code { get; set; }
        public int status_id { get; set; }
        public System.DateTime starting_date { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}
