//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tally_Sheet_Details
    {
        public int tally_sheet_details_id { get; set; }
        public int tally_sheet_id { get; set; }
        public string way_bill_code { get; set; }
        public string importer_name { get; set; }
        public string goods_name { get; set; }
        public string unit_of_measure { get; set; }
        public int total_quantity { get; set; }
        public bool is_damaged { get; set; }
    }
}
