//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_penalty_Display2
    {
        public int temp_penalty__display2_id { get; set; }
        public int way_bill_id { get; set; }
        public int Goods_Id { get; set; }
        public string goods_name { get; set; }
        public string Levy_Name { get; set; }
        public string Levy_Type { get; set; }
        public string Levy { get; set; }
        public string Actua_Levy { get; set; }
        public string Total_Levi { get; set; }
        public string Sum_Levies { get; set; }
    }
}
