//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puntland_Port_Taxation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Way_Bill
    {
        public int way_bill_id { get; set; }
        public string way_bill_code { get; set; }
        public string way_bill_name { get; set; }
        public int import_id { get; set; }
        public int importer_id { get; set; }
        public bool is_calculated { get; set; }
        public string mark { get; set; }
    }
}
